### ISSUE TITLE
What font can be used to display the unicode glyph in the screenshot?

### ISSUE THREAD

**Issue by xulongwu4** [DataDrake/waterlog#1]
Thanks for the library. I tried using it and I couldn't get the Unicode glyph displayed correctly in my terminal. Can you tell me which font you used to display them in your screenshot? Thanks.

**Comment by DataDrake** [comment]
Any of the patched `powerline-fonts` will do: https://github.com/powerline/fonts

Specifically, I am using the Source Code Pro variant.

**Comment by xulongwu4** [comment]
I see. Thanks very much. I will try it out.
